### ISSUE TITLE
Support generic npm modules

### ISSUE THREAD

**Issue by mindrones** [mindrones/timely-dependency-graph#7]
- [ ] support all types of version range (#1)
- [ ] support releases not sorted by time (#3)
- [ ] implement a loader strategy (#4)
- [ ] choose a solution to show a long list of modules (#5)
- [ ] add a router to detect module name (#6)
